tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    NAME_MAX_LEN = 128
    name = models.CharField(max_length=NAME_MAX_LEN, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TTILE_MAX_LEN = 128
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TTILE_MAX_LEN)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LEN, help_text="Please enter the category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TTILE_MAX_LEN, help_text="Please enter the title of the page")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
import uuid

from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime


def index(request):
    # - means descending order, remove - is ascending order
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[0:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)
    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
        print(context_dict)
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):

    """
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})
    """
    print("进入函数")
    if request.method == 'POST':
        category_name = request.POST['category_name']
        Category.objects.create(name=category_name, slug=uuid.uuid1)
        Category.save()
        print("保存category")
        return redirect('rango/')
    print("返回添加页面")
    return render(request, 'rango/add_category.html')


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect('/rango/')

    """
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        print(request.POST['title'])
        print(request.POST['url'])
        print("slug", category_name_slug)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
            else:
                print(form.errors)
    
    """
    if request.method == 'POST':
        title = request.POST['title']
        print(title)
        url = request.POST['url']
        Page.objects.create(title=title, url=url, category=category)
        return redirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))

    context_dict = {'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    """
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rango/register.html', context={'user_form': user_form,
                                                           'profile_form': profile_form,
                                                           'registered': registered})
    """

    registered = False
    if request.method == 'POST':
        print(request.POST['username'])
        print(request.POST['email'])
        print(request.POST['password'])
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    return render(request, 'rango/register.html', locals())


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print('username:', username)
        print('password:', password)
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled")
        else:
            print(f'Invalid login details: {username}, {password}')
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
<h1>Rango says.....</h1>
<div>
    here is the about page.<br />
    This is Sen Zou's practice for Django
    <p>Visits: {{ visits }}</p>
</div>
<br/>
<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango"/>
<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a cat" />
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}
<html lang="en">

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block%}

    <!--add background-->
    <div id="Layer1" style="position:absolute; width:100%; height:100%; background-color: snow; z-index:-1" >
            <img src="{% static 'images/background_4.jpg' %}" height="100%" width="100%" alt=""/>
    </div>

    <h1>Add a Category</h1>
    <!--
    <div class="col-md-offset-4">
        <form id="category_form1" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
    -->

    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
      {% csrf_token %}
      <div class="form-row align-items-center">
        <div class="col-md-6">
          <input type="text" class="form-control col-md-12" id="inlineFormInput" name="category_name" placeholder="Please enter the category name ">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-2">Submit</button>
        </div>
      </div>
    </form>

{% endblock %}
</html>

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{%  load static %}
{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}

    <!--add background-->
    <div id="Layer1" style="position:absolute; width:100%; height:100%; background-color: snow; z-index:-1" >
            <img src="{% static 'images/background_3.jpg' %}" height="100%" width="100%" alt=""/>
    </div>


    <h1>Add A Page to {{ category.name }}</h1>
    <!--
    <div>
        <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page"/>
        </form>
    </div> -->

    <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
        {% csrf_token %}
      <div class="form-row align-items-center">
        <div class="col-3">
            <label class="sr-only" for="inlineFormInput">Name</label>
            <input type="text" class="form-control mb-2" name="title" id="inlineFormInput" placeholder="Please enter the title of the page">
        </div>
          <div class="col-3">
              <label class="sr-only" for="inlineFormInput">Name</label>
              <input type="text" class="form-control mb-2" name="url" id="inlineFormInput" placeholder="Please enter the URL of the page">
          </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-primary mb-2">Submit</button>
        </div>
      </div>
    </form>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
    <!--don't move -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!--navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Category
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:index' %}">HomePage</a>
            </li>
            <!-- if user has logged in show logout link, otherwise show login and register -->
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:logout' %}">Logout</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:register' %}">Register</a>
                </li>

            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Please enter a category" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    {% block body_block %}
    {% endblock %}

    <!--
    <div>
        {% block sidebar_block %}
            {% get_category_list %}
        {% endblock %}
    </div>
    <hr/>
    -->


    <!--
    <div>
        <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            {% else %}
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
    -->
</body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul>
{% if categories%}
    {% for c in categories %}
        {% if c == current_category %}
        <li>
        <strong>
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
        {% else %}
        <li>
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <!--
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
    -->
    {% for page in pages %}
        <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{page.title}}</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="{{ page.url }}" class="btn btn-primary">Go</a>
              </div>
        </div>
    {% endfor %}
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}<br/>
    {% if user.is_authenticated %}
    <button type="button" onclick="window.location.href='{% url 'rango:add_page' category.slug%}'" class="btn btn-primary offset-sm-0">Add Page</button>
    {% endif %}
    {% else %}
    The specified category does not exist
    {% endif %}

{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block%}
    <!--carousel -->
    <!--
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'images/javaPic.jpeg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'images/rango.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src=".../800x400?auto=yes&bg=555&fg=333&text=Third slide" alt="Third slide">
        </div>
      </div>
    </div>
    <br/>
    -->

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'images/javaPicture.jpeg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'images/banner_3.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'images/banner_2.jpg' %}" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>



    <!--
    <h1>Rango says...</h1>
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
        <br/>
        <strong>{{ boldmessage }}</strong><br/>
    </div>
    -->

    <!--
    <div>
        <h2>Most Liked Categories</h2>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li><a href="/rango/category/{{ category.slug }}">{{ category.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present</strong>
    {% endif %}
    </div>
    -->

    <!--
    <div>
        <h2>Most Viewed Pages</h2>
     {% if pages %}
        <ul>
         {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
         {% endfor %}
        </ul>
      {% else %}
         <strong>There are no pages present</strong>
      {% endif %}
    </div>
    -->


    <div class="container">
      <div class="row">
        <div class="col-sm">
              <ul class="list-group">
                  <li class="list-group-item"><h2>Most Liked Categories</h2></li>
                  {% for category in categories %}
                      <li class="list-group-item"><a href="/rango/category/{{ category.slug }}">{{ category.name }}</a></li>
                  {% endfor %}
              </ul>
        </div>

        <div class="col-sm">
              <ul class="list-group">
                  <li class="list-group-item"><h2>Most Viewed Pages</h2></li>
                  {% for page in pages %}
                      <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
                  {% endfor %}
              </ul>
        </div>
      </div>
    </div>



{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block%}

    <!--add background-->
    <div id="Layer1" style="position:absolute; width:100%; height:100%; background-color: snow; z-index:-1" >
            <img src="{% static 'images/background_2.jpg' %}" height="100%" width="100%" alt=""/>
    </div>


<!--
<h1 class="text-center">Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}" class="text-center">
    {% csrf_token %}
    Username:<input type="text" name="username" value="" size="50" /><br>
    Password: <input type="password" name="password" value="" size="50" /><br>
    <input type="submit" value="submit" />
</form>
-->


<form action="{% url 'rango:login' %}" method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    <h1>Login to Rango</h1>
    <div class="form-group col-md-6">
        <label for="uname" class="control-label col-md-5">username</label>
        <div class="col-md-6 col-md-offset-4">
            <input type="text" id="uname" name="username" class="form-control" placeholder="please enter username">
        </div>
    </div>
    <div class="form-group col-md-6">
        <label for="password" class="control-label col-md-5">password</label>
        <div class="col-md-6">
            <input type="password" id="password" name="password" class="form-control" placeholder="please enter password">
        </div>
    </div>
    <div class="form-group col-md-6">
        <button type="submit" class="btn btn-primary" >Login</button>
    </div>
</form>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}





{% block body_block %}

    <div id="Layer1" style="position:absolute; width:100%; height:100%; background-color: snow; z-index:-1" >
        <img src="{% static 'images/background_1.jpg' %}" height="100%" width="100%" alt=""/>
    </div>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />

{% else %}

    <!--
    <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="submit" value="Register" />
    </form>
    -->
<div class="container">
    <div class="form-group col-md-5">
        <h1><strong>Register here!</strong><br /></h1>
    </div>
    <form id="user_form" method="post" action="{% url 'rango:register' %}">
        {% csrf_token %}
        <div class="form-group col-md-5">
            <label for="myusername">username:</label>
            <input type="text" class="form-control" name="username" placeholder="please enter username"/>
            <label >Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</label>
        </div>
        <div class="form-group col-md-5">
            <label for="myemail">email:</label>
            <input type="email" class="form-control" name="email" placeholder="please enter email"/>
        </div>
        <div class="form-group col-md-5">
            <label for="mypwd">password:</label>
            <input type="password" class="form-control" name="password" placeholder="please enter password"/>
        </div>
        <div class="form-group col-md-5">
            <button type="submit" class="btn btn-primary">register</button>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <h1>Restricted Page</h1>
You can see this page, because you have logged in
SenZou is here!
{% endblock %}